extraction:
  cpp:
    after_prepare: 
      - python report.py 8
  cobol:
    after_prepare: 
      - python report.py 8
  csharp:
    after_prepare: 
      - python report.py 8
  java:
    after_prepare: 
      - python report.py 8
  javascript:
    after_prepare: 
      - python report.py 8
  python:
    after_prepare: 
      - python report.py 8
